### ISSUE TITLE
Invalid Syntax When Update to 4.10.1

### ISSUE THREAD

**Issue by marufkilic** [ntropy-network/ntropy-sdk#124]
* Ntropy SDK version: 4.10.1
* Python version:  3.7.1
* Operating System: Ubuntu 18.04

### Description

I update ntropy sdk version 4.8.3 to **4.10.1** then got it this error when try to run backend. error points to ntropy side. If there anyone who know this problem ?

### What I Did

```
Upgrade sdk version from 4.8.3 to 4.10.1
```
![image](https://user-images.githubusercontent.com/8219567/192234201-c23744bc-4de3-4bf2-9f34-bf85fda7204c.png)

**Comment by yoheioka** [comment]
It looks like that syntax is only supported by >= python 3.8.
Can the code be fixed to support >= python 3.6 per 
https://github.com/ntropy-network/ntropy-sdk/blob/69f9aa6d4ff1f1a1845dedd3f5732ad1609a31b8/setup.py#L23

**Comment by jorge-pessoa** [comment]
Thank you for the information. We've fixed this particular issue in #125 . The CI was also moved to python 3.6 to ensure that compatibility is automatically checked in future. 

Version 4.10.2 has been released containing this fix.
